apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
    - name: node
      image: node:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
    - name: chrome
      image: zenika/alpine-chrome:86-with-node-12
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
